name: CI

on:
  push:
    branches: [main]
    tags-ignore: ["*"]
    paths-ignore:
      - screenshots/**
      - LICENSE
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint:
    name: "PR: Conventional Commits"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - uses: EmbarkStudios/cargo-deny-action@v2
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          arguments: "--no-default-features"
          manifest-path: "./pulldown-cmark-mdcat/Cargo.toml"
      - name: Build manpage
        uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: asciidoctor -b manpage -a reproducible --warnings adcat.1.adoc
      - name: Validate manpage
        run: man -l --warnings=w --pager=cat adcat.1
        env:
          MANWIDTH: 80

  test:
    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev
      - name: Build
        run: cargo build --workspace --all-targets --locked
      - name: Clippy
        run: cargo clippy --workspace --all-targets --locked
      - name: Test
        run: cargo test --workspace --locked
      - name: Docs
        if: runner.os != 'Windows'
        run: cargo doc --workspace --locked
      - name: Smoke test
        run: cargo run -- sample/common-mark.md
